/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *chordTab;
    QPushButton *chordsButton;
    QComboBox *ChordsTypeComboBox;
    QLabel *ChordsOutputLabel;
    QComboBox *ChordsNoteComboBox;
    QWidget *scaleTab;
    QComboBox *ScaleTypeComboBox;
    QPushButton *scalesButton;
    QLabel *ScaleOutputLabel;
    QComboBox *ScaleNoteComboBox;
    QWidget *progressionTab;
    QComboBox *ProgNoteComboBox;
    QPushButton *addChordButton;
    QComboBox *ProgTypeComboBox;
    QPushButton *chord_1;
    QPushButton *chord_2;
    QPushButton *chord_3;
    QPushButton *chord_4;
    QPushButton *remove_1;
    QPushButton *remove_2;
    QPushButton *remove_3;
    QPushButton *remove_4;
    QLabel *notelabel_00;
    QLabel *notelabel_02;
    QLabel *notelabel_01;
    QLabel *notelabel_05;
    QLabel *notelabel_04;
    QLabel *notelabel_09;
    QLabel *notelabel_11;
    QLabel *notelabel_12;
    QLabel *notelabel_21;
    QLabel *notelabel_19;
    QLabel *notelabel_16;
    QLabel *notelabel_24;
    QLabel *notelabel_23;
    QLabel *notelabel_17;
    QLabel *notelabel_26;
    QLabel *notelabel_14;
    QLabel *notelabel_03;
    QLabel *notelabel_06;
    QLabel *notelabel_08;
    QLabel *notelabel_10;
    QLabel *notelabel_13;
    QLabel *notelabel_15;
    QLabel *notelabel_22;
    QLabel *notelabel_18;
    QLabel *notelabel_20;
    QLabel *notelabel_25;
    QLabel *notelabel_07;
    QLabel *notelabel_2;
    QLabel *piano_14;
    QLabel *piano_24;
    QLabel *piano_17;
    QLabel *piano_09;
    QLabel *piano_16;
    QLabel *piano_18;
    QLabel *piano_08;
    QLabel *piano_10;
    QLabel *piano_05;
    QLabel *notelabel_34;
    QLabel *piano_02;
    QLabel *piano_03;
    QLabel *piano_26;
    QLabel *piano_11;
    QLabel *piano_04;
    QLabel *piano_06;
    QLabel *piano_13;
    QLabel *piano_12;
    QLabel *piano_23;
    QLabel *piano_25;
    QLabel *piano_21;
    QLabel *piano_19;
    QLabel *piano_07;
    QLabel *piano_15;
    QLabel *piano_00;
    QLabel *piano_20;
    QLabel *piano_01;
    QLabel *piano_22;
    QPushButton *playButton;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(521, 343);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(0, 170, 521, 151));
        chordTab = new QWidget();
        chordTab->setObjectName(QString::fromUtf8("chordTab"));
        chordsButton = new QPushButton(chordTab);
        chordsButton->setObjectName(QString::fromUtf8("chordsButton"));
        chordsButton->setGeometry(QRect(390, 80, 111, 31));
        ChordsTypeComboBox = new QComboBox(chordTab);
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->addItem(QString());
        ChordsTypeComboBox->setObjectName(QString::fromUtf8("ChordsTypeComboBox"));
        ChordsTypeComboBox->setGeometry(QRect(160, 80, 201, 31));
        ChordsOutputLabel = new QLabel(chordTab);
        ChordsOutputLabel->setObjectName(QString::fromUtf8("ChordsOutputLabel"));
        ChordsOutputLabel->setGeometry(QRect(50, 20, 411, 41));
        ChordsOutputLabel->setFrameShape(QFrame::Box);
        ChordsOutputLabel->setAlignment(Qt::AlignCenter);
        ChordsOutputLabel->setOpenExternalLinks(false);
        ChordsNoteComboBox = new QComboBox(chordTab);
        ChordsNoteComboBox->addItem(QString());
        ChordsNoteComboBox->addItem(QString());
        ChordsNoteComboBox->addItem(QString());
        ChordsNoteComboBox->addItem(QString());
        ChordsNoteComboBox->addItem(QString());
        ChordsNoteComboBox->addItem(QString());
        ChordsNoteComboBox->addItem(QString());
        ChordsNoteComboBox->addItem(QString());
        ChordsNoteComboBox->addItem(QString());
        ChordsNoteComboBox->addItem(QString());
        ChordsNoteComboBox->addItem(QString());
        ChordsNoteComboBox->addItem(QString());
        ChordsNoteComboBox->setObjectName(QString::fromUtf8("ChordsNoteComboBox"));
        ChordsNoteComboBox->setGeometry(QRect(20, 80, 111, 31));
        tabWidget->addTab(chordTab, QString());
        scaleTab = new QWidget();
        scaleTab->setObjectName(QString::fromUtf8("scaleTab"));
        ScaleTypeComboBox = new QComboBox(scaleTab);
        ScaleTypeComboBox->addItem(QString());
        ScaleTypeComboBox->addItem(QString());
        ScaleTypeComboBox->addItem(QString());
        ScaleTypeComboBox->addItem(QString());
        ScaleTypeComboBox->addItem(QString());
        ScaleTypeComboBox->addItem(QString());
        ScaleTypeComboBox->addItem(QString());
        ScaleTypeComboBox->addItem(QString());
        ScaleTypeComboBox->addItem(QString());
        ScaleTypeComboBox->addItem(QString());
        ScaleTypeComboBox->addItem(QString());
        ScaleTypeComboBox->addItem(QString());
        ScaleTypeComboBox->addItem(QString());
        ScaleTypeComboBox->addItem(QString());
        ScaleTypeComboBox->setObjectName(QString::fromUtf8("ScaleTypeComboBox"));
        ScaleTypeComboBox->setGeometry(QRect(160, 80, 201, 31));
        scalesButton = new QPushButton(scaleTab);
        scalesButton->setObjectName(QString::fromUtf8("scalesButton"));
        scalesButton->setGeometry(QRect(390, 80, 111, 31));
        ScaleOutputLabel = new QLabel(scaleTab);
        ScaleOutputLabel->setObjectName(QString::fromUtf8("ScaleOutputLabel"));
        ScaleOutputLabel->setGeometry(QRect(50, 20, 411, 41));
        ScaleOutputLabel->setFrameShape(QFrame::Box);
        ScaleOutputLabel->setAlignment(Qt::AlignCenter);
        ScaleOutputLabel->setOpenExternalLinks(false);
        ScaleNoteComboBox = new QComboBox(scaleTab);
        ScaleNoteComboBox->addItem(QString());
        ScaleNoteComboBox->addItem(QString());
        ScaleNoteComboBox->addItem(QString());
        ScaleNoteComboBox->addItem(QString());
        ScaleNoteComboBox->addItem(QString());
        ScaleNoteComboBox->addItem(QString());
        ScaleNoteComboBox->addItem(QString());
        ScaleNoteComboBox->addItem(QString());
        ScaleNoteComboBox->addItem(QString());
        ScaleNoteComboBox->addItem(QString());
        ScaleNoteComboBox->addItem(QString());
        ScaleNoteComboBox->addItem(QString());
        ScaleNoteComboBox->setObjectName(QString::fromUtf8("ScaleNoteComboBox"));
        ScaleNoteComboBox->setGeometry(QRect(20, 80, 111, 31));
        tabWidget->addTab(scaleTab, QString());
        progressionTab = new QWidget();
        progressionTab->setObjectName(QString::fromUtf8("progressionTab"));
        ProgNoteComboBox = new QComboBox(progressionTab);
        ProgNoteComboBox->addItem(QString());
        ProgNoteComboBox->addItem(QString());
        ProgNoteComboBox->addItem(QString());
        ProgNoteComboBox->addItem(QString());
        ProgNoteComboBox->addItem(QString());
        ProgNoteComboBox->addItem(QString());
        ProgNoteComboBox->addItem(QString());
        ProgNoteComboBox->addItem(QString());
        ProgNoteComboBox->addItem(QString());
        ProgNoteComboBox->addItem(QString());
        ProgNoteComboBox->addItem(QString());
        ProgNoteComboBox->addItem(QString());
        ProgNoteComboBox->setObjectName(QString::fromUtf8("ProgNoteComboBox"));
        ProgNoteComboBox->setGeometry(QRect(20, 80, 111, 31));
        addChordButton = new QPushButton(progressionTab);
        addChordButton->setObjectName(QString::fromUtf8("addChordButton"));
        addChordButton->setGeometry(QRect(390, 80, 111, 31));
        ProgTypeComboBox = new QComboBox(progressionTab);
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->addItem(QString());
        ProgTypeComboBox->setObjectName(QString::fromUtf8("ProgTypeComboBox"));
        ProgTypeComboBox->setGeometry(QRect(160, 80, 201, 31));
        chord_1 = new QPushButton(progressionTab);
        chord_1->setObjectName(QString::fromUtf8("chord_1"));
        chord_1->setGeometry(QRect(110, 10, 51, 41));
        chord_2 = new QPushButton(progressionTab);
        chord_2->setObjectName(QString::fromUtf8("chord_2"));
        chord_2->setGeometry(QRect(190, 10, 51, 41));
        chord_3 = new QPushButton(progressionTab);
        chord_3->setObjectName(QString::fromUtf8("chord_3"));
        chord_3->setGeometry(QRect(270, 10, 51, 41));
        chord_4 = new QPushButton(progressionTab);
        chord_4->setObjectName(QString::fromUtf8("chord_4"));
        chord_4->setGeometry(QRect(350, 10, 51, 41));
        remove_1 = new QPushButton(progressionTab);
        remove_1->setObjectName(QString::fromUtf8("remove_1"));
        remove_1->setGeometry(QRect(120, 50, 31, 21));
        remove_1->setStyleSheet(QString::fromUtf8("text-align: center;"));
        remove_2 = new QPushButton(progressionTab);
        remove_2->setObjectName(QString::fromUtf8("remove_2"));
        remove_2->setGeometry(QRect(200, 50, 31, 21));
        remove_2->setStyleSheet(QString::fromUtf8("text-align: center;"));
        remove_3 = new QPushButton(progressionTab);
        remove_3->setObjectName(QString::fromUtf8("remove_3"));
        remove_3->setGeometry(QRect(280, 50, 31, 21));
        remove_3->setStyleSheet(QString::fromUtf8("text-align: center;"));
        remove_4 = new QPushButton(progressionTab);
        remove_4->setObjectName(QString::fromUtf8("remove_4"));
        remove_4->setGeometry(QRect(360, 50, 31, 21));
        remove_4->setStyleSheet(QString::fromUtf8("text-align: center;"));
        tabWidget->addTab(progressionTab, QString());
        notelabel_00 = new QLabel(centralWidget);
        notelabel_00->setObjectName(QString::fromUtf8("notelabel_00"));
        notelabel_00->setEnabled(false);
        notelabel_00->setGeometry(QRect(20, 20, 31, 121));
        notelabel_00->setAutoFillBackground(false);
        notelabel_00->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_00->setFrameShape(QFrame::Box);
        notelabel_00->setFrameShadow(QFrame::Plain);
        notelabel_00->setLineWidth(1);
        notelabel_00->setMidLineWidth(0);
        notelabel_00->setTextFormat(Qt::AutoText);
        notelabel_02 = new QLabel(centralWidget);
        notelabel_02->setObjectName(QString::fromUtf8("notelabel_02"));
        notelabel_02->setEnabled(false);
        notelabel_02->setGeometry(QRect(50, 20, 31, 121));
        notelabel_02->setAutoFillBackground(false);
        notelabel_02->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_02->setFrameShape(QFrame::Box);
        notelabel_02->setFrameShadow(QFrame::Plain);
        notelabel_02->setLineWidth(1);
        notelabel_02->setMidLineWidth(0);
        notelabel_02->setTextFormat(Qt::AutoText);
        notelabel_01 = new QLabel(centralWidget);
        notelabel_01->setObjectName(QString::fromUtf8("notelabel_01"));
        notelabel_01->setGeometry(QRect(40, 20, 21, 71));
        notelabel_01->setAutoFillBackground(false);
        notelabel_01->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_01->setFrameShape(QFrame::Box);
        notelabel_01->setFrameShadow(QFrame::Plain);
        notelabel_01->setLineWidth(1);
        notelabel_01->setMidLineWidth(0);
        notelabel_01->setTextFormat(Qt::AutoText);
        notelabel_05 = new QLabel(centralWidget);
        notelabel_05->setObjectName(QString::fromUtf8("notelabel_05"));
        notelabel_05->setEnabled(false);
        notelabel_05->setGeometry(QRect(110, 20, 31, 121));
        notelabel_05->setAutoFillBackground(false);
        notelabel_05->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_05->setFrameShape(QFrame::Box);
        notelabel_05->setFrameShadow(QFrame::Plain);
        notelabel_05->setLineWidth(1);
        notelabel_05->setMidLineWidth(0);
        notelabel_05->setTextFormat(Qt::AutoText);
        notelabel_04 = new QLabel(centralWidget);
        notelabel_04->setObjectName(QString::fromUtf8("notelabel_04"));
        notelabel_04->setEnabled(false);
        notelabel_04->setGeometry(QRect(80, 20, 31, 121));
        notelabel_04->setAutoFillBackground(false);
        notelabel_04->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_04->setFrameShape(QFrame::Box);
        notelabel_04->setFrameShadow(QFrame::Plain);
        notelabel_04->setLineWidth(1);
        notelabel_04->setMidLineWidth(0);
        notelabel_04->setTextFormat(Qt::AutoText);
        notelabel_09 = new QLabel(centralWidget);
        notelabel_09->setObjectName(QString::fromUtf8("notelabel_09"));
        notelabel_09->setEnabled(false);
        notelabel_09->setGeometry(QRect(170, 20, 31, 121));
        notelabel_09->setAutoFillBackground(false);
        notelabel_09->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_09->setFrameShape(QFrame::Box);
        notelabel_09->setFrameShadow(QFrame::Plain);
        notelabel_09->setLineWidth(1);
        notelabel_09->setMidLineWidth(0);
        notelabel_09->setTextFormat(Qt::AutoText);
        notelabel_11 = new QLabel(centralWidget);
        notelabel_11->setObjectName(QString::fromUtf8("notelabel_11"));
        notelabel_11->setEnabled(false);
        notelabel_11->setGeometry(QRect(200, 20, 31, 121));
        notelabel_11->setAutoFillBackground(false);
        notelabel_11->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_11->setFrameShape(QFrame::Box);
        notelabel_11->setFrameShadow(QFrame::Plain);
        notelabel_11->setLineWidth(1);
        notelabel_11->setMidLineWidth(0);
        notelabel_11->setTextFormat(Qt::AutoText);
        notelabel_12 = new QLabel(centralWidget);
        notelabel_12->setObjectName(QString::fromUtf8("notelabel_12"));
        notelabel_12->setEnabled(false);
        notelabel_12->setGeometry(QRect(230, 20, 31, 121));
        notelabel_12->setAutoFillBackground(false);
        notelabel_12->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_12->setFrameShape(QFrame::Box);
        notelabel_12->setFrameShadow(QFrame::Plain);
        notelabel_12->setLineWidth(1);
        notelabel_12->setMidLineWidth(0);
        notelabel_12->setTextFormat(Qt::AutoText);
        notelabel_21 = new QLabel(centralWidget);
        notelabel_21->setObjectName(QString::fromUtf8("notelabel_21"));
        notelabel_21->setEnabled(false);
        notelabel_21->setGeometry(QRect(380, 20, 31, 121));
        notelabel_21->setAutoFillBackground(false);
        notelabel_21->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_21->setFrameShape(QFrame::Box);
        notelabel_21->setFrameShadow(QFrame::Plain);
        notelabel_21->setLineWidth(1);
        notelabel_21->setMidLineWidth(0);
        notelabel_21->setTextFormat(Qt::AutoText);
        notelabel_19 = new QLabel(centralWidget);
        notelabel_19->setObjectName(QString::fromUtf8("notelabel_19"));
        notelabel_19->setEnabled(false);
        notelabel_19->setGeometry(QRect(350, 20, 31, 121));
        notelabel_19->setAutoFillBackground(false);
        notelabel_19->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_19->setFrameShape(QFrame::Box);
        notelabel_19->setFrameShadow(QFrame::Plain);
        notelabel_19->setLineWidth(1);
        notelabel_19->setMidLineWidth(0);
        notelabel_19->setTextFormat(Qt::AutoText);
        notelabel_16 = new QLabel(centralWidget);
        notelabel_16->setObjectName(QString::fromUtf8("notelabel_16"));
        notelabel_16->setEnabled(false);
        notelabel_16->setGeometry(QRect(290, 20, 31, 121));
        notelabel_16->setAutoFillBackground(false);
        notelabel_16->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_16->setFrameShape(QFrame::Box);
        notelabel_16->setFrameShadow(QFrame::Plain);
        notelabel_16->setLineWidth(1);
        notelabel_16->setMidLineWidth(0);
        notelabel_16->setTextFormat(Qt::AutoText);
        notelabel_24 = new QLabel(centralWidget);
        notelabel_24->setObjectName(QString::fromUtf8("notelabel_24"));
        notelabel_24->setEnabled(false);
        notelabel_24->setGeometry(QRect(440, 20, 31, 121));
        notelabel_24->setAutoFillBackground(false);
        notelabel_24->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_24->setFrameShape(QFrame::Box);
        notelabel_24->setFrameShadow(QFrame::Plain);
        notelabel_24->setLineWidth(1);
        notelabel_24->setMidLineWidth(0);
        notelabel_24->setTextFormat(Qt::AutoText);
        notelabel_23 = new QLabel(centralWidget);
        notelabel_23->setObjectName(QString::fromUtf8("notelabel_23"));
        notelabel_23->setEnabled(false);
        notelabel_23->setGeometry(QRect(410, 20, 31, 121));
        notelabel_23->setAutoFillBackground(false);
        notelabel_23->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_23->setFrameShape(QFrame::Box);
        notelabel_23->setFrameShadow(QFrame::Plain);
        notelabel_23->setLineWidth(1);
        notelabel_23->setMidLineWidth(0);
        notelabel_23->setTextFormat(Qt::AutoText);
        notelabel_17 = new QLabel(centralWidget);
        notelabel_17->setObjectName(QString::fromUtf8("notelabel_17"));
        notelabel_17->setEnabled(false);
        notelabel_17->setGeometry(QRect(320, 20, 31, 121));
        notelabel_17->setAutoFillBackground(false);
        notelabel_17->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_17->setFrameShape(QFrame::Box);
        notelabel_17->setFrameShadow(QFrame::Plain);
        notelabel_17->setLineWidth(1);
        notelabel_17->setMidLineWidth(0);
        notelabel_17->setTextFormat(Qt::AutoText);
        notelabel_26 = new QLabel(centralWidget);
        notelabel_26->setObjectName(QString::fromUtf8("notelabel_26"));
        notelabel_26->setEnabled(false);
        notelabel_26->setGeometry(QRect(470, 20, 31, 121));
        notelabel_26->setAutoFillBackground(false);
        notelabel_26->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_26->setFrameShape(QFrame::Box);
        notelabel_26->setFrameShadow(QFrame::Plain);
        notelabel_26->setLineWidth(1);
        notelabel_26->setMidLineWidth(0);
        notelabel_26->setTextFormat(Qt::AutoText);
        notelabel_14 = new QLabel(centralWidget);
        notelabel_14->setObjectName(QString::fromUtf8("notelabel_14"));
        notelabel_14->setEnabled(false);
        notelabel_14->setGeometry(QRect(260, 20, 31, 121));
        notelabel_14->setAutoFillBackground(false);
        notelabel_14->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_14->setFrameShape(QFrame::Box);
        notelabel_14->setFrameShadow(QFrame::Plain);
        notelabel_14->setLineWidth(1);
        notelabel_14->setMidLineWidth(0);
        notelabel_14->setTextFormat(Qt::AutoText);
        notelabel_03 = new QLabel(centralWidget);
        notelabel_03->setObjectName(QString::fromUtf8("notelabel_03"));
        notelabel_03->setGeometry(QRect(70, 20, 21, 71));
        notelabel_03->setAutoFillBackground(false);
        notelabel_03->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_03->setFrameShape(QFrame::Box);
        notelabel_03->setFrameShadow(QFrame::Plain);
        notelabel_03->setLineWidth(1);
        notelabel_03->setMidLineWidth(0);
        notelabel_03->setTextFormat(Qt::AutoText);
        notelabel_06 = new QLabel(centralWidget);
        notelabel_06->setObjectName(QString::fromUtf8("notelabel_06"));
        notelabel_06->setGeometry(QRect(130, 20, 21, 71));
        notelabel_06->setAutoFillBackground(false);
        notelabel_06->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_06->setFrameShape(QFrame::Box);
        notelabel_06->setFrameShadow(QFrame::Plain);
        notelabel_06->setLineWidth(1);
        notelabel_06->setMidLineWidth(0);
        notelabel_06->setTextFormat(Qt::AutoText);
        notelabel_08 = new QLabel(centralWidget);
        notelabel_08->setObjectName(QString::fromUtf8("notelabel_08"));
        notelabel_08->setGeometry(QRect(160, 20, 21, 71));
        notelabel_08->setAutoFillBackground(false);
        notelabel_08->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_08->setFrameShape(QFrame::Box);
        notelabel_08->setFrameShadow(QFrame::Plain);
        notelabel_08->setLineWidth(1);
        notelabel_08->setMidLineWidth(0);
        notelabel_08->setTextFormat(Qt::AutoText);
        notelabel_10 = new QLabel(centralWidget);
        notelabel_10->setObjectName(QString::fromUtf8("notelabel_10"));
        notelabel_10->setGeometry(QRect(190, 20, 21, 71));
        notelabel_10->setAutoFillBackground(false);
        notelabel_10->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_10->setFrameShape(QFrame::Box);
        notelabel_10->setFrameShadow(QFrame::Plain);
        notelabel_10->setLineWidth(1);
        notelabel_10->setMidLineWidth(0);
        notelabel_10->setTextFormat(Qt::AutoText);
        notelabel_13 = new QLabel(centralWidget);
        notelabel_13->setObjectName(QString::fromUtf8("notelabel_13"));
        notelabel_13->setGeometry(QRect(250, 20, 21, 71));
        notelabel_13->setAutoFillBackground(false);
        notelabel_13->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_13->setFrameShape(QFrame::Box);
        notelabel_13->setFrameShadow(QFrame::Plain);
        notelabel_13->setLineWidth(1);
        notelabel_13->setMidLineWidth(0);
        notelabel_13->setTextFormat(Qt::AutoText);
        notelabel_15 = new QLabel(centralWidget);
        notelabel_15->setObjectName(QString::fromUtf8("notelabel_15"));
        notelabel_15->setGeometry(QRect(280, 20, 21, 71));
        notelabel_15->setAutoFillBackground(false);
        notelabel_15->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_15->setFrameShape(QFrame::Box);
        notelabel_15->setFrameShadow(QFrame::Plain);
        notelabel_15->setLineWidth(1);
        notelabel_15->setMidLineWidth(0);
        notelabel_15->setTextFormat(Qt::AutoText);
        notelabel_22 = new QLabel(centralWidget);
        notelabel_22->setObjectName(QString::fromUtf8("notelabel_22"));
        notelabel_22->setGeometry(QRect(400, 20, 21, 71));
        notelabel_22->setAutoFillBackground(false);
        notelabel_22->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_22->setFrameShape(QFrame::Box);
        notelabel_22->setFrameShadow(QFrame::Plain);
        notelabel_22->setLineWidth(1);
        notelabel_22->setMidLineWidth(0);
        notelabel_22->setTextFormat(Qt::AutoText);
        notelabel_18 = new QLabel(centralWidget);
        notelabel_18->setObjectName(QString::fromUtf8("notelabel_18"));
        notelabel_18->setGeometry(QRect(340, 20, 21, 71));
        notelabel_18->setAutoFillBackground(false);
        notelabel_18->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_18->setFrameShape(QFrame::Box);
        notelabel_18->setFrameShadow(QFrame::Plain);
        notelabel_18->setLineWidth(1);
        notelabel_18->setMidLineWidth(0);
        notelabel_18->setTextFormat(Qt::AutoText);
        notelabel_20 = new QLabel(centralWidget);
        notelabel_20->setObjectName(QString::fromUtf8("notelabel_20"));
        notelabel_20->setGeometry(QRect(370, 20, 21, 71));
        notelabel_20->setAutoFillBackground(false);
        notelabel_20->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_20->setFrameShape(QFrame::Box);
        notelabel_20->setFrameShadow(QFrame::Plain);
        notelabel_20->setLineWidth(1);
        notelabel_20->setMidLineWidth(0);
        notelabel_20->setTextFormat(Qt::AutoText);
        notelabel_25 = new QLabel(centralWidget);
        notelabel_25->setObjectName(QString::fromUtf8("notelabel_25"));
        notelabel_25->setGeometry(QRect(460, 20, 21, 71));
        notelabel_25->setAutoFillBackground(false);
        notelabel_25->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_25->setFrameShape(QFrame::Box);
        notelabel_25->setFrameShadow(QFrame::Plain);
        notelabel_25->setLineWidth(1);
        notelabel_25->setMidLineWidth(0);
        notelabel_25->setTextFormat(Qt::AutoText);
        notelabel_07 = new QLabel(centralWidget);
        notelabel_07->setObjectName(QString::fromUtf8("notelabel_07"));
        notelabel_07->setEnabled(false);
        notelabel_07->setGeometry(QRect(140, 20, 31, 121));
        notelabel_07->setAutoFillBackground(false);
        notelabel_07->setStyleSheet(QString::fromUtf8("background-color: #3385ff"));
        notelabel_07->setFrameShape(QFrame::Box);
        notelabel_07->setFrameShadow(QFrame::Plain);
        notelabel_07->setLineWidth(1);
        notelabel_07->setMidLineWidth(0);
        notelabel_07->setTextFormat(Qt::AutoText);
        notelabel_2 = new QLabel(centralWidget);
        notelabel_2->setObjectName(QString::fromUtf8("notelabel_2"));
        notelabel_2->setGeometry(QRect(40, 20, 21, 71));
        notelabel_2->setAutoFillBackground(false);
        notelabel_2->setStyleSheet(QString::fromUtf8("background-color: black;"));
        notelabel_2->setFrameShape(QFrame::Box);
        notelabel_2->setFrameShadow(QFrame::Plain);
        notelabel_2->setLineWidth(1);
        notelabel_2->setMidLineWidth(0);
        notelabel_2->setTextFormat(Qt::AutoText);
        piano_14 = new QLabel(centralWidget);
        piano_14->setObjectName(QString::fromUtf8("piano_14"));
        piano_14->setGeometry(QRect(260, 20, 31, 121));
        piano_14->setAutoFillBackground(false);
        piano_14->setStyleSheet(QString::fromUtf8("background-color: white"));
        piano_14->setFrameShape(QFrame::Box);
        piano_14->setFrameShadow(QFrame::Plain);
        piano_14->setLineWidth(1);
        piano_14->setMidLineWidth(0);
        piano_14->setTextFormat(Qt::AutoText);
        piano_24 = new QLabel(centralWidget);
        piano_24->setObjectName(QString::fromUtf8("piano_24"));
        piano_24->setGeometry(QRect(440, 20, 31, 121));
        piano_24->setAutoFillBackground(false);
        piano_24->setStyleSheet(QString::fromUtf8("background-color: white"));
        piano_24->setFrameShape(QFrame::Box);
        piano_24->setFrameShadow(QFrame::Plain);
        piano_24->setLineWidth(1);
        piano_24->setMidLineWidth(0);
        piano_24->setTextFormat(Qt::AutoText);
        piano_17 = new QLabel(centralWidget);
        piano_17->setObjectName(QString::fromUtf8("piano_17"));
        piano_17->setGeometry(QRect(320, 20, 31, 121));
        piano_17->setAutoFillBackground(false);
        piano_17->setStyleSheet(QString::fromUtf8("background-color: white"));
        piano_17->setFrameShape(QFrame::Box);
        piano_17->setFrameShadow(QFrame::Plain);
        piano_17->setLineWidth(1);
        piano_17->setMidLineWidth(0);
        piano_17->setTextFormat(Qt::AutoText);
        piano_09 = new QLabel(centralWidget);
        piano_09->setObjectName(QString::fromUtf8("piano_09"));
        piano_09->setGeometry(QRect(170, 20, 31, 121));
        piano_09->setAutoFillBackground(false);
        piano_09->setStyleSheet(QString::fromUtf8("background-color: white"));
        piano_09->setFrameShape(QFrame::Box);
        piano_09->setFrameShadow(QFrame::Plain);
        piano_09->setLineWidth(1);
        piano_09->setMidLineWidth(0);
        piano_09->setTextFormat(Qt::AutoText);
        piano_16 = new QLabel(centralWidget);
        piano_16->setObjectName(QString::fromUtf8("piano_16"));
        piano_16->setGeometry(QRect(290, 20, 31, 121));
        piano_16->setAutoFillBackground(false);
        piano_16->setStyleSheet(QString::fromUtf8("background-color: white"));
        piano_16->setFrameShape(QFrame::Box);
        piano_16->setFrameShadow(QFrame::Plain);
        piano_16->setLineWidth(1);
        piano_16->setMidLineWidth(0);
        piano_16->setTextFormat(Qt::AutoText);
        piano_18 = new QLabel(centralWidget);
        piano_18->setObjectName(QString::fromUtf8("piano_18"));
        piano_18->setGeometry(QRect(340, 20, 21, 71));
        piano_18->setAutoFillBackground(false);
        piano_18->setStyleSheet(QString::fromUtf8("background-color: black"));
        piano_18->setFrameShape(QFrame::Box);
        piano_18->setFrameShadow(QFrame::Plain);
        piano_18->setLineWidth(1);
        piano_18->setMidLineWidth(0);
        piano_18->setTextFormat(Qt::AutoText);
        piano_08 = new QLabel(centralWidget);
        piano_08->setObjectName(QString::fromUtf8("piano_08"));
        piano_08->setGeometry(QRect(160, 20, 21, 71));
        piano_08->setAutoFillBackground(false);
        piano_08->setStyleSheet(QString::fromUtf8("background-color: black"));
        piano_08->setFrameShape(QFrame::Box);
        piano_08->setFrameShadow(QFrame::Plain);
        piano_08->setLineWidth(1);
        piano_08->setMidLineWidth(0);
        piano_08->setTextFormat(Qt::AutoText);
        piano_10 = new QLabel(centralWidget);
        piano_10->setObjectName(QString::fromUtf8("piano_10"));
        piano_10->setGeometry(QRect(190, 20, 21, 71));
        piano_10->setAutoFillBackground(false);
        piano_10->setStyleSheet(QString::fromUtf8("background-color: black"));
        piano_10->setFrameShape(QFrame::Box);
        piano_10->setFrameShadow(QFrame::Plain);
        piano_10->setLineWidth(1);
        piano_10->setMidLineWidth(0);
        piano_10->setTextFormat(Qt::AutoText);
        piano_05 = new QLabel(centralWidget);
        piano_05->setObjectName(QString::fromUtf8("piano_05"));
        piano_05->setGeometry(QRect(110, 20, 31, 121));
        piano_05->setAutoFillBackground(false);
        piano_05->setStyleSheet(QString::fromUtf8("background-color: white"));
        piano_05->setFrameShape(QFrame::Box);
        piano_05->setFrameShadow(QFrame::Plain);
        piano_05->setLineWidth(1);
        piano_05->setMidLineWidth(0);
        piano_05->setTextFormat(Qt::AutoText);
        notelabel_34 = new QLabel(centralWidget);
        notelabel_34->setObjectName(QString::fromUtf8("notelabel_34"));
        notelabel_34->setGeometry(QRect(400, 20, 21, 71));
        notelabel_34->setAutoFillBackground(false);
        notelabel_34->setStyleSheet(QString::fromUtf8("background-color: black;"));
        notelabel_34->setFrameShape(QFrame::Box);
        notelabel_34->setFrameShadow(QFrame::Plain);
        notelabel_34->setLineWidth(1);
        notelabel_34->setMidLineWidth(0);
        notelabel_34->setTextFormat(Qt::AutoText);
        piano_02 = new QLabel(centralWidget);
        piano_02->setObjectName(QString::fromUtf8("piano_02"));
        piano_02->setGeometry(QRect(50, 20, 31, 121));
        piano_02->setAutoFillBackground(false);
        piano_02->setStyleSheet(QString::fromUtf8("background-color: white"));
        piano_02->setFrameShape(QFrame::Box);
        piano_02->setFrameShadow(QFrame::Plain);
        piano_02->setLineWidth(1);
        piano_02->setMidLineWidth(0);
        piano_02->setTextFormat(Qt::AutoText);
        piano_03 = new QLabel(centralWidget);
        piano_03->setObjectName(QString::fromUtf8("piano_03"));
        piano_03->setGeometry(QRect(70, 20, 21, 71));
        piano_03->setAutoFillBackground(false);
        piano_03->setStyleSheet(QString::fromUtf8("background-color: black"));
        piano_03->setFrameShape(QFrame::Box);
        piano_03->setFrameShadow(QFrame::Plain);
        piano_03->setLineWidth(1);
        piano_03->setMidLineWidth(0);
        piano_03->setTextFormat(Qt::AutoText);
        piano_26 = new QLabel(centralWidget);
        piano_26->setObjectName(QString::fromUtf8("piano_26"));
        piano_26->setGeometry(QRect(470, 20, 31, 121));
        piano_26->setAutoFillBackground(false);
        piano_26->setStyleSheet(QString::fromUtf8("background-color: white"));
        piano_26->setFrameShape(QFrame::Box);
        piano_26->setFrameShadow(QFrame::Plain);
        piano_26->setLineWidth(1);
        piano_26->setMidLineWidth(0);
        piano_26->setTextFormat(Qt::AutoText);
        piano_11 = new QLabel(centralWidget);
        piano_11->setObjectName(QString::fromUtf8("piano_11"));
        piano_11->setGeometry(QRect(200, 20, 31, 121));
        piano_11->setAutoFillBackground(false);
        piano_11->setStyleSheet(QString::fromUtf8("background-color: white"));
        piano_11->setFrameShape(QFrame::Box);
        piano_11->setFrameShadow(QFrame::Plain);
        piano_11->setLineWidth(1);
        piano_11->setMidLineWidth(0);
        piano_11->setTextFormat(Qt::AutoText);
        piano_04 = new QLabel(centralWidget);
        piano_04->setObjectName(QString::fromUtf8("piano_04"));
        piano_04->setGeometry(QRect(80, 20, 31, 121));
        piano_04->setAutoFillBackground(false);
        piano_04->setStyleSheet(QString::fromUtf8("background-color: white"));
        piano_04->setFrameShape(QFrame::Box);
        piano_04->setFrameShadow(QFrame::Plain);
        piano_04->setLineWidth(1);
        piano_04->setMidLineWidth(0);
        piano_04->setTextFormat(Qt::AutoText);
        piano_06 = new QLabel(centralWidget);
        piano_06->setObjectName(QString::fromUtf8("piano_06"));
        piano_06->setGeometry(QRect(130, 20, 21, 71));
        piano_06->setAutoFillBackground(false);
        piano_06->setStyleSheet(QString::fromUtf8("background-color: black"));
        piano_06->setFrameShape(QFrame::Box);
        piano_06->setFrameShadow(QFrame::Plain);
        piano_06->setLineWidth(1);
        piano_06->setMidLineWidth(0);
        piano_06->setTextFormat(Qt::AutoText);
        piano_13 = new QLabel(centralWidget);
        piano_13->setObjectName(QString::fromUtf8("piano_13"));
        piano_13->setGeometry(QRect(250, 20, 21, 71));
        piano_13->setAutoFillBackground(false);
        piano_13->setStyleSheet(QString::fromUtf8("background-color: black"));
        piano_13->setFrameShape(QFrame::Box);
        piano_13->setFrameShadow(QFrame::Plain);
        piano_13->setLineWidth(1);
        piano_13->setMidLineWidth(0);
        piano_13->setTextFormat(Qt::AutoText);
        piano_12 = new QLabel(centralWidget);
        piano_12->setObjectName(QString::fromUtf8("piano_12"));
        piano_12->setGeometry(QRect(230, 20, 31, 121));
        piano_12->setAutoFillBackground(false);
        piano_12->setStyleSheet(QString::fromUtf8("background-color: white"));
        piano_12->setFrameShape(QFrame::Box);
        piano_12->setFrameShadow(QFrame::Plain);
        piano_12->setLineWidth(1);
        piano_12->setMidLineWidth(0);
        piano_12->setTextFormat(Qt::AutoText);
        piano_23 = new QLabel(centralWidget);
        piano_23->setObjectName(QString::fromUtf8("piano_23"));
        piano_23->setGeometry(QRect(410, 20, 31, 121));
        piano_23->setAutoFillBackground(false);
        piano_23->setStyleSheet(QString::fromUtf8("background-color: white"));
        piano_23->setFrameShape(QFrame::Box);
        piano_23->setFrameShadow(QFrame::Plain);
        piano_23->setLineWidth(1);
        piano_23->setMidLineWidth(0);
        piano_23->setTextFormat(Qt::AutoText);
        piano_25 = new QLabel(centralWidget);
        piano_25->setObjectName(QString::fromUtf8("piano_25"));
        piano_25->setGeometry(QRect(460, 20, 21, 71));
        piano_25->setAutoFillBackground(false);
        piano_25->setStyleSheet(QString::fromUtf8("background-color: black"));
        piano_25->setFrameShape(QFrame::Box);
        piano_25->setFrameShadow(QFrame::Plain);
        piano_25->setLineWidth(1);
        piano_25->setMidLineWidth(0);
        piano_25->setTextFormat(Qt::AutoText);
        piano_21 = new QLabel(centralWidget);
        piano_21->setObjectName(QString::fromUtf8("piano_21"));
        piano_21->setGeometry(QRect(380, 20, 31, 121));
        piano_21->setAutoFillBackground(false);
        piano_21->setStyleSheet(QString::fromUtf8("background-color: white"));
        piano_21->setFrameShape(QFrame::Box);
        piano_21->setFrameShadow(QFrame::Plain);
        piano_21->setLineWidth(1);
        piano_21->setMidLineWidth(0);
        piano_21->setTextFormat(Qt::AutoText);
        piano_19 = new QLabel(centralWidget);
        piano_19->setObjectName(QString::fromUtf8("piano_19"));
        piano_19->setGeometry(QRect(350, 20, 31, 121));
        piano_19->setAutoFillBackground(false);
        piano_19->setStyleSheet(QString::fromUtf8("background-color: white"));
        piano_19->setFrameShape(QFrame::Box);
        piano_19->setFrameShadow(QFrame::Plain);
        piano_19->setLineWidth(1);
        piano_19->setMidLineWidth(0);
        piano_19->setTextFormat(Qt::AutoText);
        piano_07 = new QLabel(centralWidget);
        piano_07->setObjectName(QString::fromUtf8("piano_07"));
        piano_07->setGeometry(QRect(140, 20, 31, 121));
        piano_07->setAutoFillBackground(false);
        piano_07->setStyleSheet(QString::fromUtf8("background-color: white"));
        piano_07->setFrameShape(QFrame::Box);
        piano_07->setFrameShadow(QFrame::Plain);
        piano_07->setLineWidth(1);
        piano_07->setMidLineWidth(0);
        piano_07->setTextFormat(Qt::AutoText);
        piano_15 = new QLabel(centralWidget);
        piano_15->setObjectName(QString::fromUtf8("piano_15"));
        piano_15->setGeometry(QRect(280, 20, 21, 71));
        piano_15->setAutoFillBackground(false);
        piano_15->setStyleSheet(QString::fromUtf8("background-color: black"));
        piano_15->setFrameShape(QFrame::Box);
        piano_15->setFrameShadow(QFrame::Plain);
        piano_15->setLineWidth(1);
        piano_15->setMidLineWidth(0);
        piano_15->setTextFormat(Qt::AutoText);
        piano_00 = new QLabel(centralWidget);
        piano_00->setObjectName(QString::fromUtf8("piano_00"));
        piano_00->setGeometry(QRect(20, 20, 31, 121));
        piano_00->setAutoFillBackground(false);
        piano_00->setStyleSheet(QString::fromUtf8("background-color: white"));
        piano_00->setFrameShape(QFrame::Box);
        piano_00->setFrameShadow(QFrame::Plain);
        piano_00->setLineWidth(1);
        piano_00->setMidLineWidth(0);
        piano_00->setTextFormat(Qt::AutoText);
        piano_20 = new QLabel(centralWidget);
        piano_20->setObjectName(QString::fromUtf8("piano_20"));
        piano_20->setGeometry(QRect(370, 20, 21, 71));
        piano_20->setAutoFillBackground(false);
        piano_20->setStyleSheet(QString::fromUtf8("background-color: black"));
        piano_20->setFrameShape(QFrame::Box);
        piano_20->setFrameShadow(QFrame::Plain);
        piano_20->setLineWidth(1);
        piano_20->setMidLineWidth(0);
        piano_20->setTextFormat(Qt::AutoText);
        piano_01 = new QLabel(centralWidget);
        piano_01->setObjectName(QString::fromUtf8("piano_01"));
        piano_01->setGeometry(QRect(40, 20, 21, 71));
        piano_01->setAutoFillBackground(false);
        piano_01->setStyleSheet(QString::fromUtf8("background-color: black"));
        piano_01->setFrameShape(QFrame::Box);
        piano_01->setFrameShadow(QFrame::Plain);
        piano_01->setLineWidth(1);
        piano_01->setMidLineWidth(0);
        piano_01->setTextFormat(Qt::AutoText);
        piano_22 = new QLabel(centralWidget);
        piano_22->setObjectName(QString::fromUtf8("piano_22"));
        piano_22->setGeometry(QRect(400, 20, 21, 71));
        piano_22->setAutoFillBackground(false);
        piano_22->setStyleSheet(QString::fromUtf8("background-color: black"));
        piano_22->setFrameShape(QFrame::Box);
        piano_22->setFrameShadow(QFrame::Plain);
        piano_22->setLineWidth(1);
        piano_22->setMidLineWidth(0);
        piano_22->setTextFormat(Qt::AutoText);
        playButton = new QPushButton(centralWidget);
        playButton->setObjectName(QString::fromUtf8("playButton"));
        playButton->setGeometry(QRect(464, 150, 41, 23));
        MainWindow->setCentralWidget(centralWidget);
        tabWidget->raise();
        notelabel_2->raise();
        piano_14->raise();
        piano_24->raise();
        piano_17->raise();
        piano_09->raise();
        piano_16->raise();
        piano_05->raise();
        notelabel_34->raise();
        piano_02->raise();
        piano_26->raise();
        piano_11->raise();
        piano_04->raise();
        piano_12->raise();
        piano_23->raise();
        piano_21->raise();
        piano_19->raise();
        piano_07->raise();
        piano_00->raise();
        notelabel_00->raise();
        notelabel_09->raise();
        notelabel_14->raise();
        notelabel_04->raise();
        notelabel_12->raise();
        notelabel_21->raise();
        notelabel_16->raise();
        notelabel_19->raise();
        notelabel_24->raise();
        notelabel_26->raise();
        notelabel_23->raise();
        notelabel_11->raise();
        notelabel_05->raise();
        notelabel_17->raise();
        notelabel_07->raise();
        notelabel_02->raise();
        piano_10->raise();
        piano_03->raise();
        piano_15->raise();
        piano_22->raise();
        piano_25->raise();
        piano_18->raise();
        piano_01->raise();
        piano_08->raise();
        piano_06->raise();
        piano_20->raise();
        piano_13->raise();
        notelabel_06->raise();
        notelabel_03->raise();
        notelabel_10->raise();
        notelabel_18->raise();
        notelabel_20->raise();
        notelabel_22->raise();
        notelabel_25->raise();
        notelabel_15->raise();
        notelabel_08->raise();
        notelabel_01->raise();
        notelabel_13->raise();
        playButton->raise();
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Piano Helper", nullptr));
        chordsButton->setText(QApplication::translate("MainWindow", "Find Chord", nullptr));
        ChordsTypeComboBox->setItemText(0, QApplication::translate("MainWindow", "Major", nullptr));
        ChordsTypeComboBox->setItemText(1, QApplication::translate("MainWindow", "Maj7", nullptr));
        ChordsTypeComboBox->setItemText(2, QApplication::translate("MainWindow", "Maj9", nullptr));
        ChordsTypeComboBox->setItemText(3, QApplication::translate("MainWindow", "Maj11", nullptr));
        ChordsTypeComboBox->setItemText(4, QApplication::translate("MainWindow", "Maj13", nullptr));
        ChordsTypeComboBox->setItemText(5, QApplication::translate("MainWindow", "Minor", nullptr));
        ChordsTypeComboBox->setItemText(6, QApplication::translate("MainWindow", "Min7", nullptr));
        ChordsTypeComboBox->setItemText(7, QApplication::translate("MainWindow", "Min9", nullptr));
        ChordsTypeComboBox->setItemText(8, QApplication::translate("MainWindow", "Min11", nullptr));
        ChordsTypeComboBox->setItemText(9, QApplication::translate("MainWindow", "Min13", nullptr));
        ChordsTypeComboBox->setItemText(10, QApplication::translate("MainWindow", "d7", nullptr));
        ChordsTypeComboBox->setItemText(11, QApplication::translate("MainWindow", "d9", nullptr));
        ChordsTypeComboBox->setItemText(12, QApplication::translate("MainWindow", "d11", nullptr));
        ChordsTypeComboBox->setItemText(13, QApplication::translate("MainWindow", "d13", nullptr));
        ChordsTypeComboBox->setItemText(14, QApplication::translate("MainWindow", "Diminished", nullptr));
        ChordsTypeComboBox->setItemText(15, QApplication::translate("MainWindow", "Dim7", nullptr));
        ChordsTypeComboBox->setItemText(16, QApplication::translate("MainWindow", "Min9(b5)", nullptr));
        ChordsTypeComboBox->setItemText(17, QApplication::translate("MainWindow", "Min11(b5)", nullptr));
        ChordsTypeComboBox->setItemText(18, QApplication::translate("MainWindow", "Min13(b5)", nullptr));

        ChordsOutputLabel->setText(QString());
        ChordsNoteComboBox->setItemText(0, QApplication::translate("MainWindow", "C", nullptr));
        ChordsNoteComboBox->setItemText(1, QApplication::translate("MainWindow", "C#/Db", nullptr));
        ChordsNoteComboBox->setItemText(2, QApplication::translate("MainWindow", "D", nullptr));
        ChordsNoteComboBox->setItemText(3, QApplication::translate("MainWindow", "D#/Eb", nullptr));
        ChordsNoteComboBox->setItemText(4, QApplication::translate("MainWindow", "E", nullptr));
        ChordsNoteComboBox->setItemText(5, QApplication::translate("MainWindow", "F", nullptr));
        ChordsNoteComboBox->setItemText(6, QApplication::translate("MainWindow", "F#/Gb", nullptr));
        ChordsNoteComboBox->setItemText(7, QApplication::translate("MainWindow", "G", nullptr));
        ChordsNoteComboBox->setItemText(8, QApplication::translate("MainWindow", "G#/Ab", nullptr));
        ChordsNoteComboBox->setItemText(9, QApplication::translate("MainWindow", "A", nullptr));
        ChordsNoteComboBox->setItemText(10, QApplication::translate("MainWindow", "A#/Bb", nullptr));
        ChordsNoteComboBox->setItemText(11, QApplication::translate("MainWindow", "B", nullptr));

        tabWidget->setTabText(tabWidget->indexOf(chordTab), QApplication::translate("MainWindow", "Chords", nullptr));
        ScaleTypeComboBox->setItemText(0, QApplication::translate("MainWindow", "Ionian (Major)", nullptr));
        ScaleTypeComboBox->setItemText(1, QApplication::translate("MainWindow", "Dorian", nullptr));
        ScaleTypeComboBox->setItemText(2, QApplication::translate("MainWindow", "Phrygian", nullptr));
        ScaleTypeComboBox->setItemText(3, QApplication::translate("MainWindow", "Lydian", nullptr));
        ScaleTypeComboBox->setItemText(4, QApplication::translate("MainWindow", "Mixolydian", nullptr));
        ScaleTypeComboBox->setItemText(5, QApplication::translate("MainWindow", "Aeolean (Minor)", nullptr));
        ScaleTypeComboBox->setItemText(6, QApplication::translate("MainWindow", "Locrian", nullptr));
        ScaleTypeComboBox->setItemText(7, QApplication::translate("MainWindow", "Major Pentatonic", nullptr));
        ScaleTypeComboBox->setItemText(8, QApplication::translate("MainWindow", "Minor Pentatonic", nullptr));
        ScaleTypeComboBox->setItemText(9, QApplication::translate("MainWindow", "Melodic Minor (Ascending)", nullptr));
        ScaleTypeComboBox->setItemText(10, QApplication::translate("MainWindow", "Harmonic Minor", nullptr));
        ScaleTypeComboBox->setItemText(11, QApplication::translate("MainWindow", "Bebop Dominant", nullptr));
        ScaleTypeComboBox->setItemText(12, QApplication::translate("MainWindow", "Bebop Minor", nullptr));
        ScaleTypeComboBox->setItemText(13, QApplication::translate("MainWindow", "Bebop Major", nullptr));

        scalesButton->setText(QApplication::translate("MainWindow", "Find Scale", nullptr));
        ScaleOutputLabel->setText(QString());
        ScaleNoteComboBox->setItemText(0, QApplication::translate("MainWindow", "C", nullptr));
        ScaleNoteComboBox->setItemText(1, QApplication::translate("MainWindow", "C#/Db", nullptr));
        ScaleNoteComboBox->setItemText(2, QApplication::translate("MainWindow", "D", nullptr));
        ScaleNoteComboBox->setItemText(3, QApplication::translate("MainWindow", "D#/Eb", nullptr));
        ScaleNoteComboBox->setItemText(4, QApplication::translate("MainWindow", "E", nullptr));
        ScaleNoteComboBox->setItemText(5, QApplication::translate("MainWindow", "F", nullptr));
        ScaleNoteComboBox->setItemText(6, QApplication::translate("MainWindow", "F#/Gb", nullptr));
        ScaleNoteComboBox->setItemText(7, QApplication::translate("MainWindow", "G", nullptr));
        ScaleNoteComboBox->setItemText(8, QApplication::translate("MainWindow", "G#/Ab", nullptr));
        ScaleNoteComboBox->setItemText(9, QApplication::translate("MainWindow", "A", nullptr));
        ScaleNoteComboBox->setItemText(10, QApplication::translate("MainWindow", "A#/Bb", nullptr));
        ScaleNoteComboBox->setItemText(11, QApplication::translate("MainWindow", "B", nullptr));

        tabWidget->setTabText(tabWidget->indexOf(scaleTab), QApplication::translate("MainWindow", "Scales", nullptr));
        ProgNoteComboBox->setItemText(0, QApplication::translate("MainWindow", "C", nullptr));
        ProgNoteComboBox->setItemText(1, QApplication::translate("MainWindow", "C#/Db", nullptr));
        ProgNoteComboBox->setItemText(2, QApplication::translate("MainWindow", "D", nullptr));
        ProgNoteComboBox->setItemText(3, QApplication::translate("MainWindow", "D#/Eb", nullptr));
        ProgNoteComboBox->setItemText(4, QApplication::translate("MainWindow", "E", nullptr));
        ProgNoteComboBox->setItemText(5, QApplication::translate("MainWindow", "F", nullptr));
        ProgNoteComboBox->setItemText(6, QApplication::translate("MainWindow", "F#/Gb", nullptr));
        ProgNoteComboBox->setItemText(7, QApplication::translate("MainWindow", "G", nullptr));
        ProgNoteComboBox->setItemText(8, QApplication::translate("MainWindow", "G#/Ab", nullptr));
        ProgNoteComboBox->setItemText(9, QApplication::translate("MainWindow", "A", nullptr));
        ProgNoteComboBox->setItemText(10, QApplication::translate("MainWindow", "A#/Bb", nullptr));
        ProgNoteComboBox->setItemText(11, QApplication::translate("MainWindow", "B", nullptr));

        addChordButton->setText(QApplication::translate("MainWindow", "Add Chord", nullptr));
        ProgTypeComboBox->setItemText(0, QApplication::translate("MainWindow", "Major", nullptr));
        ProgTypeComboBox->setItemText(1, QApplication::translate("MainWindow", "Maj7", nullptr));
        ProgTypeComboBox->setItemText(2, QApplication::translate("MainWindow", "Maj9", nullptr));
        ProgTypeComboBox->setItemText(3, QApplication::translate("MainWindow", "Maj11", nullptr));
        ProgTypeComboBox->setItemText(4, QApplication::translate("MainWindow", "Maj13", nullptr));
        ProgTypeComboBox->setItemText(5, QApplication::translate("MainWindow", "Minor", nullptr));
        ProgTypeComboBox->setItemText(6, QApplication::translate("MainWindow", "Min7", nullptr));
        ProgTypeComboBox->setItemText(7, QApplication::translate("MainWindow", "Min9", nullptr));
        ProgTypeComboBox->setItemText(8, QApplication::translate("MainWindow", "Min11", nullptr));
        ProgTypeComboBox->setItemText(9, QApplication::translate("MainWindow", "Min13", nullptr));
        ProgTypeComboBox->setItemText(10, QApplication::translate("MainWindow", "d7", nullptr));
        ProgTypeComboBox->setItemText(11, QApplication::translate("MainWindow", "d9", nullptr));
        ProgTypeComboBox->setItemText(12, QApplication::translate("MainWindow", "d11", nullptr));
        ProgTypeComboBox->setItemText(13, QApplication::translate("MainWindow", "d13", nullptr));
        ProgTypeComboBox->setItemText(14, QApplication::translate("MainWindow", "Diminished", nullptr));
        ProgTypeComboBox->setItemText(15, QApplication::translate("MainWindow", "Dim7", nullptr));
        ProgTypeComboBox->setItemText(16, QApplication::translate("MainWindow", "Min9(b5)", nullptr));
        ProgTypeComboBox->setItemText(17, QApplication::translate("MainWindow", "Min11(b5)", nullptr));
        ProgTypeComboBox->setItemText(18, QApplication::translate("MainWindow", "Min13(b5)", nullptr));

        chord_1->setText(QApplication::translate("MainWindow", "Chord 1", nullptr));
        chord_2->setText(QApplication::translate("MainWindow", "Chord 2", nullptr));
        chord_3->setText(QApplication::translate("MainWindow", "Chord 3", nullptr));
        chord_4->setText(QApplication::translate("MainWindow", "Chord 4", nullptr));
        remove_1->setText(QApplication::translate("MainWindow", "X", nullptr));
        remove_2->setText(QApplication::translate("MainWindow", "X", nullptr));
        remove_3->setText(QApplication::translate("MainWindow", "X", nullptr));
        remove_4->setText(QApplication::translate("MainWindow", "X", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(progressionTab), QApplication::translate("MainWindow", "Chord Progression", nullptr));
        notelabel_00->setText(QString());
        notelabel_02->setText(QString());
        notelabel_01->setText(QString());
        notelabel_05->setText(QString());
        notelabel_04->setText(QString());
        notelabel_09->setText(QString());
        notelabel_11->setText(QString());
        notelabel_12->setText(QString());
        notelabel_21->setText(QString());
        notelabel_19->setText(QString());
        notelabel_16->setText(QString());
        notelabel_24->setText(QString());
        notelabel_23->setText(QString());
        notelabel_17->setText(QString());
        notelabel_26->setText(QString());
        notelabel_14->setText(QString());
        notelabel_03->setText(QString());
        notelabel_06->setText(QString());
        notelabel_08->setText(QString());
        notelabel_10->setText(QString());
        notelabel_13->setText(QString());
        notelabel_15->setText(QString());
        notelabel_22->setText(QString());
        notelabel_18->setText(QString());
        notelabel_20->setText(QString());
        notelabel_25->setText(QString());
        notelabel_07->setText(QString());
        notelabel_2->setText(QString());
        piano_14->setText(QString());
        piano_24->setText(QString());
        piano_17->setText(QString());
        piano_09->setText(QString());
        piano_16->setText(QString());
        piano_18->setText(QString());
        piano_08->setText(QString());
        piano_10->setText(QString());
        piano_05->setText(QString());
        notelabel_34->setText(QString());
        piano_02->setText(QString());
        piano_03->setText(QString());
        piano_26->setText(QString());
        piano_11->setText(QString());
        piano_04->setText(QString());
        piano_06->setText(QString());
        piano_13->setText(QString());
        piano_12->setText(QString());
        piano_23->setText(QString());
        piano_25->setText(QString());
        piano_21->setText(QString());
        piano_19->setText(QString());
        piano_07->setText(QString());
        piano_15->setText(QString());
        piano_00->setText(QString());
        piano_20->setText(QString());
        piano_01->setText(QString());
        piano_22->setText(QString());
        playButton->setText(QApplication::translate("MainWindow", "Play", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
